/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.directorOperativo;

import controlador.ControladorBus;
import controlador.ControladorRuta;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import logica.Bus;
import logica.Empleado;
import validaciones.Validaciones;

/**
 *
 * @author Joan
 */
public class VentanaDatosBus extends javax.swing.JFrame {

    JFrame ventanaAnterior;
    String operacion;
    Bus busModificar;
    ControladorRuta controladorRuta = new ControladorRuta();
    ControladorBus controladorBus = new ControladorBus();
    Validaciones validaciones = new Validaciones();
            
    public VentanaDatosBus(JFrame anterior, String operacion, Bus bus) {
        
        super("Registro/Modificacion de Bus");
        initComponents();
        
        ventanaAnterior = anterior;
        this.operacion = operacion;
        busModificar = bus;
                
        setLocationRelativeTo(null);
                     
        Calendar fecha = Calendar.getInstance();
        
        int dia, mes, año;
        dia = fecha.get(Calendar.DATE);
        mes = fecha.get(Calendar.MONTH) + 1;
        año = fecha.get(Calendar.YEAR);
        
        labelFecha.setText(dia + "/" + mes + "/" + año);
        
        reiniciarCampos();
        
        if(operacion.equals("Modificacion")){
            llenarDatosModificar();
        }
        
    }
    
    
    public void reiniciarCampos(){
        
        tfPlaca1.setText("");
        tfPlaca2.setText("");
        
        cbTipo.setSelectedIndex(0);
        spCapacidad.setValue(50);
        
        controladorRuta.obtenerCodRutas(cbRuta);
        cbRuta.setSelectedIndex(0);
        
        
    }
    
    public void llenarDatosModificar(){
        
        tfPlaca1.setEnabled(false);
        tfPlaca2.setEnabled(false);
        
        String placa = busModificar.getPlaca();           
        cbTipo.setSelectedItem(busModificar.getTipo());
        spCapacidad.setValue(busModificar.getCapacidad());
        cbRuta.setSelectedItem(busModificar.getCod_ruta());
        
        String[] placas = placa.split("-");
        
        tfPlaca1.setText(placas[0]);
        tfPlaca2.setText(placas[1]);        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        labelEslogan = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        panelInfo = new javax.swing.JPanel();
        lPlaca = new javax.swing.JLabel();
        lTelefono = new javax.swing.JLabel();
        tfPlaca1 = new javax.swing.JTextField();
        bTerminar = new javax.swing.JButton();
        bAtras = new javax.swing.JButton();
        lCapacidad = new javax.swing.JLabel();
        lPlaca1 = new javax.swing.JLabel();
        tfPlaca2 = new javax.swing.JTextField();
        cbTipo = new javax.swing.JComboBox<>();
        spCapacidad = new javax.swing.JSpinner();
        lRuta = new javax.swing.JLabel();
        cbRuta = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelPrincipal.setBackground(new java.awt.Color(0, 97, 147));

        panelSuperior.setBackground(new java.awt.Color(0, 97, 147));
        panelSuperior.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoMio.png"))); // NOI18N

        labelEslogan.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        labelEslogan.setForeground(new java.awt.Color(255, 255, 255));
        labelEslogan.setText("EL MIO ES TUYO");

        labelFecha.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEslogan, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSuperiorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSuperiorLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(labelEslogan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInfo.setBackground(new java.awt.Color(0, 97, 147));
        panelInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos del Bus", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 3, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        lPlaca.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lPlaca.setForeground(new java.awt.Color(255, 255, 255));
        lPlaca.setText("Placa:");

        lTelefono.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lTelefono.setText("Tipo:");

        tfPlaca1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPlaca1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPlaca1KeyTyped(evt);
            }
        });

        bTerminar.setBackground(new java.awt.Color(0, 97, 147));
        bTerminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/general/bTerminar.png"))); // NOI18N
        bTerminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/general/bTerminarPR.png"))); // NOI18N
        bTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTerminarActionPerformed(evt);
            }
        });

        bAtras.setBackground(new java.awt.Color(0, 97, 147));
        bAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bAtras.png"))); // NOI18N
        bAtras.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bAtrasPR.png"))); // NOI18N
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        lCapacidad.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lCapacidad.setForeground(new java.awt.Color(255, 255, 255));
        lCapacidad.setText("Capacidad:");

        lPlaca1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lPlaca1.setForeground(new java.awt.Color(255, 255, 255));
        lPlaca1.setText("-");

        tfPlaca2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPlaca2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPlaca2KeyTyped(evt);
            }
        });

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo", "Articulado", "Alimentador", "Padron" }));

        spCapacidad.setModel(new javax.swing.SpinnerNumberModel(50, 50, 80, 10));

        lRuta.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lRuta.setForeground(new java.awt.Color(255, 255, 255));
        lRuta.setText("Ruta:");

        cbRuta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una ruta" }));

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelInfoLayout.createSequentialGroup()
                        .addComponent(bAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(bTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInfoLayout.createSequentialGroup()
                                .addComponent(lPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPlaca1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelInfoLayout.createSequentialGroup()
                                .addComponent(lPlaca1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPlaca2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelInfoLayout.createSequentialGroup()
                                .addComponent(lTelefono)
                                .addGap(40, 40, 40)
                                .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelInfoLayout.createSequentialGroup()
                                .addComponent(lRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbRuta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPlaca)
                    .addComponent(tfPlaca1)
                    .addComponent(lPlaca1)
                    .addComponent(tfPlaca2)
                    .addComponent(lTelefono)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCapacidad)
                    .addComponent(spCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lRuta)
                    .addComponent(cbRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTerminarActionPerformed

        String placa1 = tfPlaca1.getText();
        String placa2 = tfPlaca2.getText();                       
        
        String placa = placa1+"-"+placa2;
        String tipo = cbTipo.getSelectedItem().toString();
        int capacidad = Integer.parseInt(spCapacidad.getValue().toString());
        String codRuta = cbRuta.getSelectedItem().toString();
        
        if((cbRuta.getSelectedIndex() == 0) || (cbTipo.getSelectedIndex() == 0) || (placa.length() != 7)){
        
            JOptionPane.showMessageDialog(null, "Información ingresada incompleta o incorrecta", "Error", JOptionPane.WARNING_MESSAGE);
                   
        }
        else{              
            
            //Si el bus ya existe y se va a registrar
            if(operacion.equals("Registro") && controladorBus.existeBus(placa)){
                JOptionPane.showMessageDialog(null, "Ya esiste un bus con la placa " + placa + " registrado", "Error", JOptionPane.WARNING_MESSAGE);
            }
            
            else{
                
                Bus newBus = new Bus(placa, capacidad, tipo, codRuta);
                int resultado = controladorBus.guardarModificarBus(newBus, operacion);
                
                if(resultado != -1){
                
                if(operacion.equals("Registro")){
                    JOptionPane.showMessageDialog(null, "Bus guardado correctamenete");
                    reiniciarCampos();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Información del bus modificada correctamente");
                    this.dispose();
                    ventanaAnterior.setVisible(true);
                    ventanaAnterior.setLocationRelativeTo(null);
            
                    VentanaVisualizarBuses vBuses = (VentanaVisualizarBuses) ventanaAnterior;
                    vBuses.llenarTablaBuses("Todos");
                }     
                
            }   
                
            } 
            
        }
        
        
        
    }//GEN-LAST:event_bTerminarActionPerformed

    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed

        int cerrar = JOptionPane.showConfirmDialog(null,"Se cancelará la operación actual\n¿Está seguro de que quiere cerrar esta ventana?", "Confirmación de cierre", JOptionPane.YES_NO_OPTION);

        if(cerrar == JOptionPane.YES_OPTION){
            this.dispose();
            ventanaAnterior.setVisible(true);
            ventanaAnterior.setLocationRelativeTo(null);
            
            VentanaVisualizarBuses vBuses = (VentanaVisualizarBuses) ventanaAnterior;
            vBuses.llenarTablaBuses("Todos");
        }
    }//GEN-LAST:event_bAtrasActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        int cerrar = JOptionPane.showConfirmDialog(null,"Se cancelará la operación actual\n¿Está seguro de que quiere cerrar esta ventana?", "Confirmación de cierre", JOptionPane.YES_NO_OPTION);

        if(cerrar == JOptionPane.YES_OPTION){
            this.dispose();
            ventanaAnterior.setVisible(true);
            ventanaAnterior.setLocationRelativeTo(null);
        }
        
    }//GEN-LAST:event_formWindowClosing

    private void tfPlaca1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPlaca1KeyTyped
        // TODO add your handling code here:
        validaciones.validarTamano(tfPlaca1, evt, 3);
        validaciones.validarLetras(evt);
        
    }//GEN-LAST:event_tfPlaca1KeyTyped

    private void tfPlaca2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPlaca2KeyTyped
        // TODO add your handling code here:
        validaciones.validarTamano(tfPlaca2, evt, 3);
        validaciones.validarNumeros(evt);
    }//GEN-LAST:event_tfPlaca2KeyTyped

    private void tfPlaca1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPlaca1KeyReleased
        
        tfPlaca1.setText(tfPlaca1.getText().toUpperCase());
        
    }//GEN-LAST:event_tfPlaca1KeyReleased

    private void tfPlaca2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPlaca2KeyReleased
                
        tfPlaca2.setText(tfPlaca2.getText().toUpperCase());
        
    }//GEN-LAST:event_tfPlaca2KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDatosBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDatosBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDatosBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDatosBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDatosBus(null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtras;
    private javax.swing.JButton bTerminar;
    private javax.swing.JComboBox<String> cbRuta;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel lCapacidad;
    private javax.swing.JLabel lPlaca;
    private javax.swing.JLabel lPlaca1;
    private javax.swing.JLabel lRuta;
    private javax.swing.JLabel lTelefono;
    private javax.swing.JLabel labelEslogan;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JSpinner spCapacidad;
    private javax.swing.JTextField tfPlaca1;
    private javax.swing.JTextField tfPlaca2;
    // End of variables declaration//GEN-END:variables
}
