/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.directorOperativo;

import controlador.ControladorEstacion;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import logica.Estacion;
import validaciones.Validaciones;

/**
 *
 * @author Joan
 */
public class VentanaVisualizarEstaciones extends javax.swing.JFrame {

    private JFrame ventanaAnterior;
    private ControladorEstacion controladorEstacion = new ControladorEstacion();
    private TableRowSorter trsFiltro;
    Validaciones validaciones = new Validaciones();
            
    public VentanaVisualizarEstaciones(JFrame anterior, boolean seleccion) {
        
        super("Lista de Estaciones");
        initComponents();
        
        ventanaAnterior = anterior;
        setLocationRelativeTo(null);
        
        Calendar fecha = Calendar.getInstance();
        
        int dia, mes, año;
        dia = fecha.get(Calendar.DATE);
        mes = fecha.get(Calendar.MONTH) + 1;
        año = fecha.get(Calendar.YEAR);
        
        labelFecha.setText(dia + "/" + mes + "/" + año);
        
        llenarTablaEstaciones();
        
        trsFiltro = new TableRowSorter(tablaEstaciones.getModel());
        tablaEstaciones.setRowSorter(trsFiltro);
        
        bSeleccionarEstacion.setVisible(seleccion);        
        bAgregarEstación.setVisible(!seleccion);
        bModificarEstación.setVisible(!seleccion);
        
        
        // Las siguientes 4 líneas, son para centrar la información de la tabla 
        ((DefaultTableCellRenderer)tablaEstaciones.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER); 
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer(); 
        tcr.setHorizontalAlignment(JLabel.CENTER); 
        tablaEstaciones.setDefaultRenderer(Object.class, tcr);
    }
    
    public void llenarTablaEstaciones(){
        
        ArrayList<Estacion> estaciones = controladorEstacion.listaEstaciones();
        
        DefaultTableModel modelo = (DefaultTableModel)tablaEstaciones.getModel();
        modelo.setRowCount(0);                
        
        if(estaciones != null){
            
            for (int i = 0; i < estaciones.size(); i++) {
                Estacion estacionActual = estaciones.get(i);
                
                Object fila[] = new Object[5];
                
                fila[0]= estacionActual.getCodigo();
                fila[1]= estacionActual.getNombre();
                fila[2]= estacionActual.getUbicacion();
                fila[3]= estacionActual.getTelefono();
                fila[4]= estacionActual.getDirector();
                                
                modelo.addRow(fila);
                
            }  
            
        }
        else{
            JOptionPane.showMessageDialog(null, "No hay estaciones registradas en la base de datos");
        }     
        
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        labelEslogan = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();
        bAtras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEstaciones = new javax.swing.JTable();
        bAgregarEstación = new javax.swing.JButton();
        bModificarEstación = new javax.swing.JButton();
        lBuscar = new javax.swing.JLabel();
        lBuscar1 = new javax.swing.JLabel();
        lBuscar2 = new javax.swing.JLabel();
        tfFiltrarCodigo = new javax.swing.JTextField();
        tfFiltrarNombre = new javax.swing.JTextField();
        bSeleccionarEstacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        panelPrincipal.setBackground(new java.awt.Color(0, 97, 147));

        panelSuperior.setBackground(new java.awt.Color(0, 97, 147));
        panelSuperior.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoMio.png"))); // NOI18N

        labelEslogan.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        labelEslogan.setForeground(new java.awt.Color(255, 255, 255));
        labelEslogan.setText("EL MIO ES TUYO");

        labelFecha.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(255, 255, 255));
        labelFecha.setText("20/11/2016");

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEslogan, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFecha))
                .addGap(25, 25, 25))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSuperiorLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(labelEslogan)
                        .addGap(18, 18, 18)
                        .addComponent(labelFecha))
                    .addGroup(panelSuperiorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        panelInferior.setBackground(new java.awt.Color(0, 97, 147));
        panelInferior.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Visualización de estaciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 3, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        panelInferior.setForeground(new java.awt.Color(255, 255, 255));

        bAtras.setBackground(new java.awt.Color(0, 97, 147));
        bAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bAtras.png"))); // NOI18N
        bAtras.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bAtrasPR.png"))); // NOI18N
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaEstaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "<html><font size=\"3\" color=\"#006193\"><b>Código</b></html>", "<html><font size=\"3\" color=\"#006193\"><b>Nombre</b></html>", "<html><font size=\"3\" color=\"#006193\"><b>Ubicación</b></html>", "<html><font size=\"3\" color=\"#006193\"><b>Teléfono</b></html>", "<html><font size=\"3\" color=\"#006193\"><b>Director</b></html>"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaEstaciones);

        bAgregarEstación.setBackground(new java.awt.Color(0, 97, 147));
        bAgregarEstación.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/general/bRegistrar.png"))); // NOI18N
        bAgregarEstación.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/general/bRegistrarPR.png"))); // NOI18N
        bAgregarEstación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarEstaciónActionPerformed(evt);
            }
        });

        bModificarEstación.setBackground(new java.awt.Color(0, 97, 147));
        bModificarEstación.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/general/bModificar.png"))); // NOI18N
        bModificarEstación.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/general/bModificarPR.png"))); // NOI18N
        bModificarEstación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarEstaciónActionPerformed(evt);
            }
        });

        lBuscar.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lBuscar.setText("Filtrar:   Por código: ");

        lBuscar1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lBuscar1.setForeground(new java.awt.Color(255, 255, 255));

        lBuscar2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lBuscar2.setForeground(new java.awt.Color(255, 255, 255));
        lBuscar2.setText("Por nombre:");

        tfFiltrarCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfFiltrarCodigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfFiltrarCodigoKeyTyped(evt);
            }
        });

        tfFiltrarNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfFiltrarNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfFiltrarNombreKeyTyped(evt);
            }
        });

        bSeleccionarEstacion.setBackground(new java.awt.Color(0, 97, 147));
        bSeleccionarEstacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/general/bSeleccionar.png"))); // NOI18N
        bSeleccionarEstacion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/general/bSeleccionarPR.png"))); // NOI18N
        bSeleccionarEstacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSeleccionarEstacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
        panelInferior.setLayout(panelInferiorLayout);
        panelInferiorLayout.setHorizontalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelInferiorLayout.createSequentialGroup()
                            .addComponent(bAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bSeleccionarEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bAgregarEstación, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bModificarEstación, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelInferiorLayout.createSequentialGroup()
                        .addComponent(lBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfFiltrarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(lBuscar2)
                        .addGap(18, 18, 18)
                        .addComponent(tfFiltrarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInferiorLayout.setVerticalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lBuscar)
                    .addComponent(lBuscar1)
                    .addComponent(lBuscar2)
                    .addComponent(tfFiltrarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFiltrarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addGap(25, 25, 25)
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAgregarEstación, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bModificarEstación, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSeleccionarEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed

        this.dispose();
        ventanaAnterior.setVisible(true);
        ventanaAnterior.setLocationRelativeTo(null);
    }//GEN-LAST:event_bAtrasActionPerformed

    private void bAgregarEstaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarEstaciónActionPerformed
        
        VentanaDatosEstacion vEstacion = new VentanaDatosEstacion(this, "Registro", null);
        vEstacion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bAgregarEstaciónActionPerformed

    private void bModificarEstaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarEstaciónActionPerformed
        
        int filaSeleccionada = tablaEstaciones.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) tablaEstaciones.getModel();               
        
        if(filaSeleccionada != -1){
            
            filaSeleccionada = tablaEstaciones.getRowSorter().convertRowIndexToModel(filaSeleccionada);
            
            int codigo = Integer.parseInt(modelo.getValueAt(filaSeleccionada, 0).toString());
            String nombre = modelo.getValueAt(filaSeleccionada, 1).toString();
            String ubicacion = modelo.getValueAt(filaSeleccionada, 2).toString();
            String telefono = modelo.getValueAt(filaSeleccionada, 3).toString();
            String director = modelo.getValueAt(filaSeleccionada, 4).toString();
            
            Estacion estacion = new Estacion(codigo, nombre, ubicacion, telefono, director);
            
            VentanaDatosEstacion vEstacion = new VentanaDatosEstacion(this, "Modificacion", estacion);
            vEstacion.setVisible(true);
            this.setVisible(false);
            
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar una estación para modificarla", "Error", JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_bModificarEstaciónActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
        this.dispose();
        ventanaAnterior.setVisible(true);
        ventanaAnterior.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowClosed

    private void tfFiltrarCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFiltrarCodigoKeyReleased
        
        int columna = 0;
        
        trsFiltro.setRowFilter(RowFilter.regexFilter(tfFiltrarCodigo.getText(), columna));
        
    }//GEN-LAST:event_tfFiltrarCodigoKeyReleased

    private void tfFiltrarNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFiltrarNombreKeyReleased
        
        int columna = 1;
        
        trsFiltro.setRowFilter(RowFilter.regexFilter(tfFiltrarNombre.getText(), columna));
        
    }//GEN-LAST:event_tfFiltrarNombreKeyReleased

    private void bSeleccionarEstacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSeleccionarEstacionActionPerformed
        
        int[] filasSeleccionadas = tablaEstaciones.getSelectedRows();
        DefaultTableModel modelo = (DefaultTableModel) tablaEstaciones.getModel();
               
        if(filasSeleccionadas.length != 0) {
            
            ArrayList<Estacion> estaciones = new ArrayList<>();
                        
            for (int i = 0; i < filasSeleccionadas.length; i++) {
                
                filasSeleccionadas[i] = tablaEstaciones.getRowSorter().convertRowIndexToModel(filasSeleccionadas[i]);
                
                int codigo = Integer.parseInt(modelo.getValueAt(filasSeleccionadas[i], 0).toString());
                String nombre = modelo.getValueAt(filasSeleccionadas[i], 1).toString();                               
                
                estaciones.add(new Estacion(codigo, nombre, "", "", ""));                
            }            
            
            VentanaDatosRuta vRuta = (VentanaDatosRuta) ventanaAnterior;
            vRuta.añadirEstaciones(estaciones);
            
            this.dispose();
            vRuta.setVisible(true);
            vRuta.setLocationRelativeTo(null);
            
        }        
        
        else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar una estación para continuar", "Error", JOptionPane.WARNING_MESSAGE);
        }
        
        
        
        
        
    }//GEN-LAST:event_bSeleccionarEstacionActionPerformed

    private void tfFiltrarNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFiltrarNombreKeyTyped
        // TODO add your handling code here:
        validaciones.validarTamano(tfFiltrarNombre, evt, 50);
    }//GEN-LAST:event_tfFiltrarNombreKeyTyped

    private void tfFiltrarCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFiltrarCodigoKeyTyped
        // TODO add your handling code here:
        validaciones.validarNumeros(evt);
    }//GEN-LAST:event_tfFiltrarCodigoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarEstaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarEstaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarEstaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarEstaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVisualizarEstaciones(null, false).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregarEstación;
    private javax.swing.JButton bAtras;
    private javax.swing.JButton bModificarEstación;
    private javax.swing.JButton bSeleccionarEstacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lBuscar;
    private javax.swing.JLabel lBuscar1;
    private javax.swing.JLabel lBuscar2;
    private javax.swing.JLabel labelEslogan;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTable tablaEstaciones;
    private javax.swing.JTextField tfFiltrarCodigo;
    private javax.swing.JTextField tfFiltrarNombre;
    // End of variables declaration//GEN-END:variables
}
