/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.gerente;

import controlador.ControladorEmpleado;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import logica.*;
import reportes.Reportes;
import validaciones.Validaciones;

/**
 *
 * @author Joan
 */
public class VentanaVisualizacionEmpleados extends javax.swing.JFrame {

    
    JFrame ventanaAnterior;
    Empleado usuarioActual;
    ControladorEmpleado contradorEmp = new ControladorEmpleado();
    TableRowSorter trsFiltro;
    Validaciones validaciones = new Validaciones();
        
    public VentanaVisualizacionEmpleados(JFrame anterior, Empleado loggeado) {
        
        super("Visualización de empleados");
        initComponents();
        ventanaAnterior = anterior;
        setLocationRelativeTo(null);        
        
        usuarioActual = loggeado;
                        
        lIDusuario.setText("Identificación: " + usuarioActual.getId());
        lNombreUsuario.setText("Nombre: " + usuarioActual.getNombre());
        lCargoUsuario.setText("Cargo: " +usuarioActual.getCargo());
               
        Calendar fecha = Calendar.getInstance();
        
        int dia, mes, año;
        dia = fecha.get(Calendar.DATE);
        mes = fecha.get(Calendar.MONTH) + 1;
        año = fecha.get(Calendar.YEAR);
        
        labelFecha.setText(dia + "/" + mes + "/" + año);    
        
        insertarInfoEmpleados();
        
        trsFiltro = new TableRowSorter(tablaEmpleados.getModel());
        tablaEmpleados.setRowSorter(trsFiltro); 
        
        if(usuarioActual.getCargo().equals("Director de Estacion")){
            botonGenerarReporteEmpleados.setVisible(false);
        }
        
        
        // Las siguientes 4 líneas, son para centrar la información de la tabla 
        ((DefaultTableCellRenderer)tablaEmpleados.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER); 
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer(); 
        tcr.setHorizontalAlignment(JLabel.CENTER); 
        tablaEmpleados.setDefaultRenderer(Object.class, tcr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        labelEslogan = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        panelDatosTrabajadorVendedor = new javax.swing.JPanel();
        lNombreUsuario = new javax.swing.JLabel();
        lIDusuario = new javax.swing.JLabel();
        lCargoUsuario = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();
        bAtras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        bRegistrarEmpleado = new javax.swing.JButton();
        bModificarEmpleado = new javax.swing.JButton();
        botonGenerarReporteEmpleados = new javax.swing.JButton();
        lBuscar = new javax.swing.JLabel();
        tfFiltroID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        panelPrincipal.setBackground(new java.awt.Color(0, 97, 147));

        panelSuperior.setBackground(new java.awt.Color(0, 97, 147));
        panelSuperior.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoMio.png"))); // NOI18N

        labelEslogan.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        labelEslogan.setForeground(new java.awt.Color(255, 255, 255));
        labelEslogan.setText("EL MIO ES TUYO");

        labelFecha.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(255, 255, 255));
        labelFecha.setText("20/11/2016");

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEslogan, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFecha))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSuperiorLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(labelEslogan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelFecha))
                    .addGroup(panelSuperiorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        panelDatosTrabajadorVendedor.setBackground(new java.awt.Color(0, 97, 147));
        panelDatosTrabajadorVendedor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos trabajador", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panelDatosTrabajadorVendedor.setForeground(new java.awt.Color(15, 59, 90));
        panelDatosTrabajadorVendedor.setPreferredSize(new java.awt.Dimension(275, 22));

        lNombreUsuario.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lNombreUsuario.setText("Nombre:");

        lIDusuario.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lIDusuario.setForeground(new java.awt.Color(255, 255, 255));
        lIDusuario.setText("Identificación:");

        lCargoUsuario.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lCargoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lCargoUsuario.setText("Cargo:");

        javax.swing.GroupLayout panelDatosTrabajadorVendedorLayout = new javax.swing.GroupLayout(panelDatosTrabajadorVendedor);
        panelDatosTrabajadorVendedor.setLayout(panelDatosTrabajadorVendedorLayout);
        panelDatosTrabajadorVendedorLayout.setHorizontalGroup(
            panelDatosTrabajadorVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosTrabajadorVendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosTrabajadorVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lIDusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addComponent(lNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lCargoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelDatosTrabajadorVendedorLayout.setVerticalGroup(
            panelDatosTrabajadorVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosTrabajadorVendedorLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lIDusuario)
                .addGap(18, 18, 18)
                .addComponent(lNombreUsuario)
                .addGap(18, 18, 18)
                .addComponent(lCargoUsuario)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        panelInferior.setBackground(new java.awt.Color(0, 97, 147));
        panelInferior.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Visualización de empleados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 3, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        panelInferior.setForeground(new java.awt.Color(255, 255, 255));

        bAtras.setBackground(new java.awt.Color(0, 97, 147));
        bAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bAtras.png"))); // NOI18N
        bAtras.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bAtrasPR.png"))); // NOI18N
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "<html><font size=\"3\" color=\"#006193\"><b>ID</b></html>", "<html><font size=\"3\" color=\"#006193\"><b>Nombre</b></html>", "<html><font size=\"3\" color=\"#006193\"><b>Dirección</b></html>", "<html><font size=\"3\" color=\"#006193\"><b>Teléfono</b></html>", "<html><font size=\"3\" color=\"#006193\"><b>Salario</b></html>", "<html><font size=\"3\" color=\"#006193\"><b>Cargo</b></html>", "<html><font size=\"3\" color=\"#006193\"><b>Estado</b></html>"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaEmpleados);
        if (tablaEmpleados.getColumnModel().getColumnCount() > 0) {
            tablaEmpleados.getColumnModel().getColumn(0).setResizable(false);
            tablaEmpleados.getColumnModel().getColumn(1).setResizable(false);
            tablaEmpleados.getColumnModel().getColumn(2).setResizable(false);
            tablaEmpleados.getColumnModel().getColumn(3).setResizable(false);
            tablaEmpleados.getColumnModel().getColumn(4).setResizable(false);
            tablaEmpleados.getColumnModel().getColumn(5).setResizable(false);
            tablaEmpleados.getColumnModel().getColumn(6).setResizable(false);
        }

        bRegistrarEmpleado.setBackground(new java.awt.Color(0, 97, 147));
        bRegistrarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/general/bRegistrar.png"))); // NOI18N
        bRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarEmpleadoActionPerformed(evt);
            }
        });

        bModificarEmpleado.setBackground(new java.awt.Color(0, 97, 147));
        bModificarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/general/bModificar.png"))); // NOI18N
        bModificarEmpleado.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/general/bModificarPR.png"))); // NOI18N
        bModificarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarEmpleadoActionPerformed(evt);
            }
        });

        botonGenerarReporteEmpleados.setBackground(new java.awt.Color(0, 97, 147));
        botonGenerarReporteEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bGenerarReporte.png"))); // NOI18N
        botonGenerarReporteEmpleados.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bGenerarReportePR.png"))); // NOI18N
        botonGenerarReporteEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerarReporteEmpleadosActionPerformed(evt);
            }
        });

        lBuscar.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lBuscar.setText("Filtrar por ID:");

        tfFiltroID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfFiltroIDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfFiltroIDKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
        panelInferior.setLayout(panelInferiorLayout);
        panelInferiorLayout.setHorizontalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInferiorLayout.createSequentialGroup()
                        .addComponent(lBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfFiltroID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelInferiorLayout.createSequentialGroup()
                        .addComponent(bAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(botonGenerarReporteEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bRegistrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(bModificarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        panelInferiorLayout.setVerticalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lBuscar)
                    .addComponent(tfFiltroID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bRegistrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGenerarReporteEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bModificarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(panelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelDatosTrabajadorVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDatosTrabajadorVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed

        this.dispose();
        ventanaAnterior.setVisible(true);
        ventanaAnterior.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_bAtrasActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        this.dispose();
        ventanaAnterior.setVisible(true);
        ventanaAnterior.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_formWindowClosed

    private void bRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarEmpleadoActionPerformed
        
        VentanaDatosEmpleado ventanaRegistro = new VentanaDatosEmpleado(this, "Registro", null);
        ventanaRegistro.setVisible(true);
        ventanaRegistro.setComboAuxiliar(usuarioActual.getCargo());
        this.setVisible(false);        
        
    }//GEN-LAST:event_bRegistrarEmpleadoActionPerformed

    private void bModificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarEmpleadoActionPerformed
        
        //Nuevo : Jhonier
        if(tablaEmpleados.getSelectedRowCount() == 1){
            
            int filaSeleccionada = tablaEmpleados.getSelectedRow();
            String identificacion = (String)tablaEmpleados.getValueAt(filaSeleccionada, 0);
                    
            Empleado empleadoModificar = contradorEmp.obtenerEmpleado(identificacion);
            VentanaDatosEmpleado ventanaRegistro = new VentanaDatosEmpleado(this, "Modificacion", empleadoModificar);
            ventanaRegistro.setVisible(true);
            this.setVisible(false);  
            
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una fila", "Warning", JOptionPane.WARNING_MESSAGE);
        } 
        
    }//GEN-LAST:event_bModificarEmpleadoActionPerformed

    private void botonGenerarReporteEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerarReporteEmpleadosActionPerformed
        
        Reportes nuevoReporte = new Reportes();
        nuevoReporte.reporteEmpleados(usuarioActual.getId(), usuarioActual.getNombre());
    }//GEN-LAST:event_botonGenerarReporteEmpleadosActionPerformed

    private void tfFiltroIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFiltroIDKeyReleased

        int columna = 0;

        trsFiltro.setRowFilter(RowFilter.regexFilter(tfFiltroID.getText(), columna));

    }//GEN-LAST:event_tfFiltroIDKeyReleased

    private void tfFiltroIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFiltroIDKeyTyped
        
        validaciones.validarTamano(tfFiltroID, evt, 10);
        validaciones.validarNumeros(evt);
        
    }//GEN-LAST:event_tfFiltroIDKeyTyped

    
    public void insertarInfoEmpleados(){
        
        if(usuarioActual.getCargo().equals("Gerente")){
            contradorEmp.informacionEmpleados(tablaEmpleados, "");
        }
        else{//el usuari loggeado es un director de estación
            //Se llena la tabla sólo con auxiliares
            String condicion = "WHERE cargo = 'Auxiliar'";
            contradorEmp.informacionEmpleados(tablaEmpleados, condicion);            
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizacionEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizacionEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizacionEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizacionEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVisualizacionEmpleados(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtras;
    private javax.swing.JButton bModificarEmpleado;
    private javax.swing.JButton bRegistrarEmpleado;
    private javax.swing.JButton botonGenerarReporteEmpleados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lBuscar;
    public javax.swing.JLabel lCargoUsuario;
    public javax.swing.JLabel lIDusuario;
    public javax.swing.JLabel lNombreUsuario;
    private javax.swing.JLabel labelEslogan;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JPanel panelDatosTrabajadorVendedor;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JTextField tfFiltroID;
    // End of variables declaration//GEN-END:variables
}
