/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.gerente;

import controlador.ControladorEmpleado;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import logica.Empleado;
import validaciones.Validaciones;

/**
 *
 * @author Joan
 */
public class VentanaDatosEmpleado extends javax.swing.JFrame {

    JFrame ventanaAnterior;
    String operacion;
    Empleado empleadoModificar;
    ControladorEmpleado controladorEmp = new ControladorEmpleado();
    Validaciones validaciones = new Validaciones();    

    public VentanaDatosEmpleado(JFrame anterior, String operacion, Empleado empleado) {
        super("Registro/Modificación de empleado");
        initComponents();

        ventanaAnterior = anterior;
        this.operacion = operacion;
        empleadoModificar = empleado;
        
        setLocationRelativeTo(null);

        Calendar date = Calendar.getInstance();

        int dia, mes, año;
        dia = date.get(Calendar.DATE);
        mes = date.get(Calendar.MONTH) + 1;
        año = date.get(Calendar.YEAR);

        labelFecha.setText(dia + "/" + mes + "/" + año);

        if (operacion.equals("Modificacion")) {
            tfidentificacion.setEnabled(false);
            bLimpiar.setEnabled(false);
            //poner los datos actuales del empleado en el campo

            tfidentificacion.setText(empleadoModificar.getId());
            tfNombre.setText(empleadoModificar.getNombre());
            tfTel.setText(empleadoModificar.getTelefono());
            tfDir.setText(empleadoModificar.getDireccion());

            String[] fecha = empleadoModificar.getFechaNacimiento().split("-");

            cbDia.setSelectedItem(fecha[0]);
            cbMes.setSelectedItem(fecha[1]);
            cbAño.setSelectedItem(fecha[2]);

            cbCargo.setSelectedItem(empleadoModificar.getCargo());
            cbEstado.setSelectedItem(empleado.getEstado());
            cbEstado.setEnabled(true);
        } 
        

    }

    public void limpiarCampos() {

        tfidentificacion.setText("");
        tfidentificacion.setText("");
        tfNombre.setText("");
        tfTel.setText("");
        tfDir.setText("");

        cbDia.setSelectedIndex(0);
        cbMes.setSelectedIndex(0);
        cbAño.setSelectedIndex(0);

        cbCargo.setSelectedIndex(0);
        cbEstado.setSelectedIndex(0);
        tfSalario.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        labelEslogan = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        panelInfo = new javax.swing.JPanel();
        lId = new javax.swing.JLabel();
        lDir = new javax.swing.JLabel();
        lTelefono = new javax.swing.JLabel();
        lfNacimiento = new javax.swing.JLabel();
        lNombre = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfidentificacion = new javax.swing.JTextField();
        tfTel = new javax.swing.JTextField();
        tfDir = new javax.swing.JTextField();
        lfNacimiento1 = new javax.swing.JLabel();
        lfNacimiento2 = new javax.swing.JLabel();
        lfNacimiento3 = new javax.swing.JLabel();
        cbDia = new javax.swing.JComboBox<>();
        cbMes = new javax.swing.JComboBox<>();
        cbAño = new javax.swing.JComboBox<>();
        bTerminar = new javax.swing.JButton();
        bLimpiar = new javax.swing.JButton();
        bAtras = new javax.swing.JButton();
        lCargo = new javax.swing.JLabel();
        cbCargo = new javax.swing.JComboBox<>();
        cbEstado = new javax.swing.JComboBox<>();
        lEstado = new javax.swing.JLabel();
        lSalario = new javax.swing.JLabel();
        tfSalario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelPrincipal.setBackground(new java.awt.Color(0, 97, 147));

        panelSuperior.setBackground(new java.awt.Color(0, 97, 147));
        panelSuperior.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoMio.png"))); // NOI18N

        labelEslogan.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        labelEslogan.setForeground(new java.awt.Color(255, 255, 255));
        labelEslogan.setText("EL MIO ES TUYO");

        labelFecha.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEslogan, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSuperiorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSuperiorLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(labelEslogan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInfo.setBackground(new java.awt.Color(0, 97, 147));
        panelInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Ingreso de datos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 3, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        lId.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lId.setForeground(new java.awt.Color(255, 255, 255));
        lId.setText("Identificación:");

        lDir.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lDir.setForeground(new java.awt.Color(255, 255, 255));
        lDir.setText("Dirección:");

        lTelefono.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lTelefono.setText("Teléfono:");

        lfNacimiento.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lfNacimiento.setForeground(new java.awt.Color(255, 255, 255));
        lfNacimiento.setText("Fecha de Nacimiento:");

        lNombre.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lNombre.setForeground(new java.awt.Color(255, 255, 255));
        lNombre.setText("Nombre:");

        tfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNombreKeyTyped(evt);
            }
        });

        tfidentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfidentificacionKeyTyped(evt);
            }
        });

        tfTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfTelKeyTyped(evt);
            }
        });

        tfDir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDirKeyTyped(evt);
            }
        });

        lfNacimiento1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lfNacimiento1.setForeground(new java.awt.Color(255, 255, 255));
        lfNacimiento1.setText("Año:");

        lfNacimiento2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lfNacimiento2.setForeground(new java.awt.Color(255, 255, 255));
        lfNacimiento2.setText("Mes:");

        lfNacimiento3.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lfNacimiento3.setForeground(new java.awt.Color(255, 255, 255));
        lfNacimiento3.setText("Día");

        cbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        cbAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005" }));

        bTerminar.setBackground(new java.awt.Color(0, 97, 147));
        bTerminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/general/bTerminar.png"))); // NOI18N
        bTerminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/general/bTerminarPR.png"))); // NOI18N
        bTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTerminarActionPerformed(evt);
            }
        });

        bLimpiar.setBackground(new java.awt.Color(0, 97, 147));
        bLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/general/bLimpiar.png"))); // NOI18N
        bLimpiar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/general/bLimpiarPR.png"))); // NOI18N
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });

        bAtras.setBackground(new java.awt.Color(0, 97, 147));
        bAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bAtras.png"))); // NOI18N
        bAtras.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bAtrasPR.png"))); // NOI18N
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        lCargo.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lCargo.setForeground(new java.awt.Color(255, 255, 255));
        lCargo.setText("Cargo:");

        cbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un cargo", "Gerente", "Director Operativo", "Director de Estacion", "Conductor", "Auxiliar" }));
        cbCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCargoActionPerformed(evt);
            }
        });

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione estado", "Activo", "Inactivo" }));
        cbEstado.setSelectedIndex(1);
        cbEstado.setEnabled(false);

        lEstado.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lEstado.setForeground(new java.awt.Color(255, 255, 255));
        lEstado.setText("Estado:");

        lSalario.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lSalario.setForeground(new java.awt.Color(255, 255, 255));
        lSalario.setText("Salario:");

        tfSalario.setEditable(false);

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addComponent(lCargo)
                        .addGap(18, 18, 18)
                        .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInfoLayout.createSequentialGroup()
                                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfTel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfidentificacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
                            .addComponent(lfNacimiento))
                        .addGap(50, 50, 50)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInfoLayout.createSequentialGroup()
                                .addComponent(lNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelInfoLayout.createSequentialGroup()
                                    .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lDir, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfDir, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addComponent(bAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInfoLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(lfNacimiento1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbAño, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelInfoLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(bLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(bTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addComponent(lfNacimiento3)
                        .addGap(18, 18, 18)
                        .addComponent(cbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lfNacimiento2)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lId)
                    .addComponent(tfidentificacion)
                    .addComponent(lNombre)
                    .addComponent(tfNombre))
                .addGap(34, 34, 34)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTelefono)
                    .addComponent(tfTel)
                    .addComponent(lDir)
                    .addComponent(tfDir))
                .addGap(25, 25, 25)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lEstado)
                        .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lfNacimiento))
                .addGap(25, 25, 25)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lfNacimiento3)
                    .addComponent(cbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lfNacimiento2)
                    .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lfNacimiento1)
                    .addComponent(cbAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lSalario)
                        .addComponent(tfSalario))
                    .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lCargo)
                        .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTerminarActionPerformed

        // Nuevo : Jhonier
        String identificacion = tfidentificacion.getText();
        String nombre = tfNombre.getText();
        String direccion = tfDir.getText();
        String telefono = tfTel.getText();

        if (identificacion.equals("") || nombre.equals("") || direccion.equals("") || telefono.equals("")
                || cbCargo.getSelectedIndex() == 0 || cbEstado.getSelectedIndex() == 0) {

            JOptionPane.showMessageDialog(null, "Debe ingresar toda la información requerida", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            int dia = Integer.parseInt(cbDia.getSelectedItem().toString());
            int mes = Integer.parseInt(cbMes.getSelectedItem().toString());
            int año = Integer.parseInt(cbAño.getSelectedItem().toString());

            String fechaNacimiento = dia + "-" + mes + "-" + año;
            String cargo = (String) cbCargo.getSelectedItem();
            String estado = (String) cbEstado.getSelectedItem();
            double salario = Double.parseDouble(tfSalario.getText());
            String password = identificacion + "-" + año;

            if (operacion.equals("Registro")) {
                controladorEmp.registrarEmpleado(identificacion, nombre, direccion, telefono, fechaNacimiento,
                        cargo, estado, salario, password);
            } else if (operacion.equals("Modificacion")) {
                controladorEmp.modificarEmpleado(identificacion, nombre, direccion, telefono, fechaNacimiento,
                        cargo, estado, salario, password);
            }
            limpiarCampos();
        }


    }//GEN-LAST:event_bTerminarActionPerformed

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed

        limpiarCampos();

    }//GEN-LAST:event_bLimpiarActionPerformed

    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed

        int cerrar = JOptionPane.showConfirmDialog(null, "Se cancelará la operación actual\n¿Está seguro de que quiere cerrar esta ventana?", "Confirmación de cierre", JOptionPane.YES_NO_OPTION);

        if (cerrar == JOptionPane.YES_OPTION) {
            this.dispose();

            VentanaVisualizacionEmpleados ventanaAnt = (VentanaVisualizacionEmpleados) ventanaAnterior;
            ventanaAnt.insertarInfoEmpleados();
            ventanaAnt.setVisible(true);
            ventanaAnt.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_bAtrasActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        int cerrar = JOptionPane.showConfirmDialog(null, "Se cancelará la operación actual\n¿Está seguro de que quiere cerrar esta ventana?", "Confirmación de cierre", JOptionPane.YES_NO_OPTION);

        if (cerrar == JOptionPane.YES_OPTION) {
            this.dispose();
            ventanaAnterior.setVisible(true);
            ventanaAnterior.setLocationRelativeTo(null);
        }

    }//GEN-LAST:event_formWindowClosing

    private void cbCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCargoActionPerformed

        // Nuevo : Jhonier
        String cargo = (String) cbCargo.getSelectedItem();
        float salGerente = 3000000;
        float salDirOp = 2000000;
        float salDirEst = 1500000;
        float salCond = 800000;
        float salAux = 900000;

        if (cargo.equalsIgnoreCase("Gerente")) {
            tfSalario.setText("" + salGerente);
        } else if (cargo.equalsIgnoreCase("Director Operativo")) {
            tfSalario.setText("" + salDirOp);
        } else if (cargo.equalsIgnoreCase("Director de Estacion")) {
            tfSalario.setText("" + salDirEst);
        } else if (cargo.equalsIgnoreCase("Auxiliar")) {
            tfSalario.setText("" + salAux);
        } else if (cargo.equalsIgnoreCase("Conductor")) {
            tfSalario.setText("" + salCond);
        } else {
            tfSalario.setText("");
        }
    }//GEN-LAST:event_cbCargoActionPerformed

    private void tfidentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfidentificacionKeyTyped
        
        validaciones.validarTamano(tfidentificacion, evt, 10);
        validaciones.validarNumeros(evt);
        
    }//GEN-LAST:event_tfidentificacionKeyTyped

    private void tfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreKeyTyped
        
        validaciones.validarTamano(tfNombre, evt, 50);
        validaciones.validarLetras(evt);
        
    }//GEN-LAST:event_tfNombreKeyTyped

    private void tfTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTelKeyTyped
        
        validaciones.validarTamano(tfTel, evt, 10);
        validaciones.validarNumeros(evt);
        
    }//GEN-LAST:event_tfTelKeyTyped

    private void tfDirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDirKeyTyped
        
        validaciones.validarTamano(tfDir, evt, 50);
        
    }//GEN-LAST:event_tfDirKeyTyped

    /**
     * @param args the command line arguments
     */
    
    /*
    Este método se encarga de colocar el comboBox de cargo de registro de empleados como 'Auxiliar'
    Este método solo sería utilizado solo desde director de Estacion
    Dado que el director de estación solo puede registrar empleados Auxiliares
    */
    public void setComboAuxiliar(String cargo){
        
        if(cargo.equals("Director de Estacion")){

            this.cbCargo.setSelectedIndex(5);
            this.cbCargo.setEnabled(false);
        }
        
        
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDatosEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDatosEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDatosEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDatosEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDatosEmpleado(null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtras;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JButton bTerminar;
    private javax.swing.JComboBox<String> cbAño;
    public javax.swing.JComboBox<String> cbCargo;
    private javax.swing.JComboBox<String> cbDia;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JLabel lCargo;
    private javax.swing.JLabel lDir;
    private javax.swing.JLabel lEstado;
    private javax.swing.JLabel lId;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lSalario;
    private javax.swing.JLabel lTelefono;
    private javax.swing.JLabel labelEslogan;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel lfNacimiento;
    private javax.swing.JLabel lfNacimiento1;
    private javax.swing.JLabel lfNacimiento2;
    private javax.swing.JLabel lfNacimiento3;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTextField tfDir;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfSalario;
    private javax.swing.JTextField tfTel;
    private javax.swing.JTextField tfidentificacion;
    // End of variables declaration//GEN-END:variables
}
