/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.gerente;

import controlador.ControladorRuta;
import gui.directorOperativo.VentanaDatosRuta;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import logica.*;
import reportes.Reportes;

/**
 *
 * @author Joan
 */
public class VentanaVisualizacionRutas extends javax.swing.JFrame {

    JFrame ventanaAnterior;
    ControladorRuta controladorRuta = new ControladorRuta();
    TableRowSorter trsFiltro;
    Empleado usuarioActual;

    public VentanaVisualizacionRutas(JFrame anterior, Empleado usuarioActual) {

        super("Visualización de Rutas");
        initComponents();

        ventanaAnterior = anterior;
        this.usuarioActual = usuarioActual;
        setLocationRelativeTo(null);

        Calendar fecha = Calendar.getInstance();

        int dia, mes, año;
        dia = fecha.get(Calendar.DATE);
        mes = fecha.get(Calendar.MONTH) + 1;
        año = fecha.get(Calendar.YEAR);

        labelFecha.setText(dia + "/" + mes + "/" + año);

        lIDusuario2.setText("Identificación: " + usuarioActual.getId());
        lNombreUsuario2.setText("Nombre: " + usuarioActual.getNombre());
        lCargoUsuario2.setText("Cargo: " + usuarioActual.getCargo());

        botoGenerarReporteRutas.setVisible(false);
        
        if (usuarioActual.getCargo().equals("Gerente")) {

            bAgregarRuta.setVisible(false);
            bModificarRuta.setVisible(false);
            botoGenerarReporteRutas.setVisible(true);

        }

        llenarTablaRutas(); // Joan

        trsFiltro = new TableRowSorter(tablaRutas.getModel());
        tablaRutas.setRowSorter(trsFiltro);

        
        // Las siguientes 4 líneas, son para centrar la información de la tabla 
        ((DefaultTableCellRenderer)tablaRutas.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER); 
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer(); 
        tcr.setHorizontalAlignment(JLabel.CENTER); 
        tablaRutas.setDefaultRenderer(Object.class, tcr);
    }

    //Joan
    public void llenarTablaRutas() {

        ArrayList<Ruta> rutas = controladorRuta.obtenerRutas();

        DefaultTableModel modelo = (DefaultTableModel) tablaRutas.getModel();
        modelo.setRowCount(0);

        System.out.println(rutas.size());

        if (rutas != null) {

            for (int i = 0; i < rutas.size(); i++) {
                Ruta rutaActual = rutas.get(i);

                Object fila[] = new Object[3];

                fila[0] = rutaActual.getCodigo();
                fila[1] = rutaActual.getNombre();
                fila[2] = rutaActual.getDescripcion();

                modelo.addRow(fila);

            }

        } else {
            JOptionPane.showMessageDialog(null, "No hay rutas registradas en la base de datos");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        labelEslogan = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        panelDatosTrabajadorVendedor = new javax.swing.JPanel();
        lNombreUsuario2 = new javax.swing.JLabel();
        lIDusuario2 = new javax.swing.JLabel();
        lCargoUsuario2 = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRutas = new javax.swing.JTable();
        bAtras = new javax.swing.JButton();
        bVerGraficoRuta = new javax.swing.JButton();
        bAgregarRuta = new javax.swing.JButton();
        bModificarRuta = new javax.swing.JButton();
        lBuscar = new javax.swing.JLabel();
        tfFiltrarCodigo = new javax.swing.JTextField();
        botoGenerarReporteRutas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        panelPrincipal.setBackground(new java.awt.Color(0, 97, 147));

        panelSuperior.setBackground(new java.awt.Color(0, 97, 147));
        panelSuperior.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoMio.png"))); // NOI18N

        labelEslogan.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        labelEslogan.setForeground(new java.awt.Color(255, 255, 255));
        labelEslogan.setText("EL MIO ES TUYO");

        labelFecha.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(255, 255, 255));
        labelFecha.setText("20/11/2016");

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEslogan, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFecha))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSuperiorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSuperiorLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(labelEslogan)
                        .addGap(18, 18, 18)
                        .addComponent(labelFecha)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDatosTrabajadorVendedor.setBackground(new java.awt.Color(0, 97, 147));
        panelDatosTrabajadorVendedor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos trabajador", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panelDatosTrabajadorVendedor.setForeground(new java.awt.Color(15, 59, 90));
        panelDatosTrabajadorVendedor.setPreferredSize(new java.awt.Dimension(275, 22));

        lNombreUsuario2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lNombreUsuario2.setForeground(new java.awt.Color(255, 255, 255));
        lNombreUsuario2.setText("Nombre:");

        lIDusuario2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lIDusuario2.setForeground(new java.awt.Color(255, 255, 255));
        lIDusuario2.setText("Identificación:");

        lCargoUsuario2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lCargoUsuario2.setForeground(new java.awt.Color(255, 255, 255));
        lCargoUsuario2.setText("Cargo:");

        javax.swing.GroupLayout panelDatosTrabajadorVendedorLayout = new javax.swing.GroupLayout(panelDatosTrabajadorVendedor);
        panelDatosTrabajadorVendedor.setLayout(panelDatosTrabajadorVendedorLayout);
        panelDatosTrabajadorVendedorLayout.setHorizontalGroup(
            panelDatosTrabajadorVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosTrabajadorVendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosTrabajadorVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lIDusuario2, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(lNombreUsuario2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lCargoUsuario2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelDatosTrabajadorVendedorLayout.setVerticalGroup(
            panelDatosTrabajadorVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosTrabajadorVendedorLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lIDusuario2)
                .addGap(18, 18, 18)
                .addComponent(lNombreUsuario2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lCargoUsuario2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panelInferior.setBackground(new java.awt.Color(0, 97, 147));
        panelInferior.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Visualización de Rutas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 3, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        panelInferior.setForeground(new java.awt.Color(255, 255, 255));

        tablaRutas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "<html><font size=\"3\" color=\"#006193\"><b>Código</b></html>", "<html><font size=\"3\" color=\"#006193\"><b>Nombre</b></html>", "<html><font size=\"3\" color=\"#006193\"><b>Descripción</b></html>"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaRutas);

        bAtras.setBackground(new java.awt.Color(0, 97, 147));
        bAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bAtras.png"))); // NOI18N
        bAtras.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bAtrasPR.png"))); // NOI18N
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        bVerGraficoRuta.setBackground(new java.awt.Color(0, 97, 147));
        bVerGraficoRuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/general/bVerGráfico.png"))); // NOI18N
        bVerGraficoRuta.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/general/bVerGráficoPR.png"))); // NOI18N
        bVerGraficoRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerGraficoRutaActionPerformed(evt);
            }
        });

        bAgregarRuta.setBackground(new java.awt.Color(0, 97, 147));
        bAgregarRuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/general/bRegistrar.png"))); // NOI18N
        bAgregarRuta.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/general/bRegistrarPR.png"))); // NOI18N
        bAgregarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarRutaActionPerformed(evt);
            }
        });

        bModificarRuta.setBackground(new java.awt.Color(0, 97, 147));
        bModificarRuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/general/bModificar.png"))); // NOI18N
        bModificarRuta.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/general/bModificarPR.png"))); // NOI18N
        bModificarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarRutaActionPerformed(evt);
            }
        });

        lBuscar.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lBuscar.setText("Filtrar por Código:");

        tfFiltrarCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfFiltrarCodigoKeyReleased(evt);
            }
        });

        botoGenerarReporteRutas.setBackground(new java.awt.Color(0, 97, 147));
        botoGenerarReporteRutas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bGenerarReporte.png"))); // NOI18N
        botoGenerarReporteRutas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bGenerarReportePR.png"))); // NOI18N
        botoGenerarReporteRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoGenerarReporteRutasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
        panelInferior.setLayout(panelInferiorLayout);
        panelInferiorLayout.setHorizontalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInferiorLayout.createSequentialGroup()
                        .addComponent(bAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(bVerGraficoRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(bAgregarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(bModificarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInferiorLayout.createSequentialGroup()
                        .addComponent(lBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfFiltrarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183)
                        .addComponent(botoGenerarReporteRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInferiorLayout.setVerticalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botoGenerarReporteRutas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lBuscar)
                        .addComponent(tfFiltrarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAgregarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInferiorLayout.createSequentialGroup()
                        .addComponent(bModificarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bAtras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(bVerGraficoRuta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(panelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelDatosTrabajadorVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelDatosTrabajadorVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed

        this.dispose();
        ventanaAnterior.setVisible(true);
        ventanaAnterior.setLocationRelativeTo(null);

    }//GEN-LAST:event_bAtrasActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        this.dispose();
        ventanaAnterior.setVisible(true);
        ventanaAnterior.setLocationRelativeTo(null);

    }//GEN-LAST:event_formWindowClosed

    //Estos dos botones son del Director Operativo

    private void bAgregarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarRutaActionPerformed

        VentanaDatosRuta vDatosRuta = new VentanaDatosRuta(this, "Registro", null);
        vDatosRuta.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_bAgregarRutaActionPerformed

    private void bModificarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarRutaActionPerformed

        int filaSeleccionada = tablaRutas.getSelectedRow();                
        
        if (filaSeleccionada != -1) {
            
            filaSeleccionada = tablaRutas.getRowSorter().convertRowIndexToModel(filaSeleccionada);

            DefaultTableModel modelo = (DefaultTableModel) tablaRutas.getModel();

            String codigo = modelo.getValueAt(filaSeleccionada, 0).toString();
            String nombre = modelo.getValueAt(filaSeleccionada, 1).toString();
            String descripcion = modelo.getValueAt(filaSeleccionada, 2).toString();

            VentanaDatosRuta vDatosRuta = new VentanaDatosRuta(this, "Modificacion", new Ruta(codigo, nombre, descripcion));

            vDatosRuta.setVisible(true);
            this.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar la ruta a modificar", "Error", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_bModificarRutaActionPerformed

    private void tfFiltrarCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFiltrarCodigoKeyReleased

        tfFiltrarCodigo.setText(tfFiltrarCodigo.getText().toUpperCase());
        
        int columna = 0;
        trsFiltro.setRowFilter(RowFilter.regexFilter(tfFiltrarCodigo.getText(), columna));

    }//GEN-LAST:event_tfFiltrarCodigoKeyReleased

    private void bVerGraficoRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerGraficoRutaActionPerformed

        if (tablaRutas.getSelectedRowCount() == 1) {

            int filaSeleccionada = tablaRutas.getSelectedRow();
                                    
            String codRuta = (String) tablaRutas.getValueAt(filaSeleccionada, 0);            

            try {
                File path = new File("src/pdf/rutas/"+codRuta+".pdf");
                Desktop.getDesktop().open(path);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error al abrir el archivo", "Error", JOptionPane.ERROR_MESSAGE);
            } catch(IllegalArgumentException ex){
                JOptionPane.showMessageDialog(null, "No fue posible localizar el archivo", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_bVerGraficoRutaActionPerformed

    private void botoGenerarReporteRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoGenerarReporteRutasActionPerformed
        Reportes nuevoReporte = new Reportes();
        nuevoReporte.reporteRutas(usuarioActual.getId(), usuarioActual.getNombre());
    }//GEN-LAST:event_botoGenerarReporteRutasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizacionRutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizacionRutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizacionRutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizacionRutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVisualizacionRutas(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregarRuta;
    private javax.swing.JButton bAtras;
    private javax.swing.JButton bModificarRuta;
    private javax.swing.JButton bVerGraficoRuta;
    private javax.swing.JButton botoGenerarReporteRutas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lBuscar;
    public javax.swing.JLabel lCargoUsuario2;
    public javax.swing.JLabel lIDusuario2;
    public javax.swing.JLabel lNombreUsuario2;
    private javax.swing.JLabel labelEslogan;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JPanel panelDatosTrabajadorVendedor;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTable tablaRutas;
    private javax.swing.JTextField tfFiltrarCodigo;
    // End of variables declaration//GEN-END:variables
}
