/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.pasajero.*;
import controlador.*;
import java.util.Calendar;
import logica.*;
      

/**
 *
 * @author Joan
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    
    
    public VentanaPrincipal() {
        super("Sistema Integrado de Transporte MIO");
        initComponents();
        
        setLocationRelativeTo(null);
        
        Calendar fecha = Calendar.getInstance();
        
        int dia, mes, año;
        dia = fecha.get(Calendar.DATE);
        mes = fecha.get(Calendar.MONTH) + 1;
        año = fecha.get(Calendar.YEAR);
        
        labelFecha.setText(dia + "/" + mes + "/" + año);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        labelEslogan = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();
        bPersonalizarTarjeta = new javax.swing.JButton();
        bModifcarDatosPasajero = new javax.swing.JButton();
        bIngresarRuta = new javax.swing.JButton();
        bConsultarSaldo = new javax.swing.JButton();
        bIngresarEmpleado = new javax.swing.JButton();
        bInformacionQueja = new javax.swing.JButton();
        bVerRutas = new javax.swing.JButton();
        bPlanViaje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(0, 97, 147));

        panelSuperior.setBackground(new java.awt.Color(0, 97, 147));
        panelSuperior.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoMio.png"))); // NOI18N

        labelEslogan.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        labelEslogan.setForeground(new java.awt.Color(255, 255, 255));
        labelEslogan.setText("EL MIO ES TUYO");

        labelFecha.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(255, 255, 255));
        labelFecha.setText("20/11/2016");

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEslogan, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFecha))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSuperiorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSuperiorLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(labelEslogan)
                        .addGap(18, 18, 18)
                        .addComponent(labelFecha)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInferior.setBackground(new java.awt.Color(0, 97, 147));
        panelInferior.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Menú Principal", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 3, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        panelInferior.setForeground(new java.awt.Color(255, 255, 255));

        bPersonalizarTarjeta.setBackground(new java.awt.Color(0, 97, 147));
        bPersonalizarTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventanaPrincipal/bPersonalizar.png"))); // NOI18N
        bPersonalizarTarjeta.setPreferredSize(new java.awt.Dimension(189, 34));
        bPersonalizarTarjeta.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventanaPrincipal/bPersonalizarPR.png"))); // NOI18N
        bPersonalizarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPersonalizarTarjetaActionPerformed(evt);
            }
        });

        bModifcarDatosPasajero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventanaPrincipal/bDatosPasajero.png"))); // NOI18N
        bModifcarDatosPasajero.setPreferredSize(new java.awt.Dimension(189, 34));
        bModifcarDatosPasajero.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventanaPrincipal/bDatosPasajeroPR.png"))); // NOI18N
        bModifcarDatosPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModifcarDatosPasajeroActionPerformed(evt);
            }
        });

        bIngresarRuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventanaPrincipal/bIngresoRuta.png"))); // NOI18N
        bIngresarRuta.setPreferredSize(new java.awt.Dimension(189, 34));
        bIngresarRuta.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventanaPrincipal/bIngresoRutaPR.png"))); // NOI18N
        bIngresarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIngresarRutaActionPerformed(evt);
            }
        });

        bConsultarSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventanaPrincipal/bConsultarSaldo.png"))); // NOI18N
        bConsultarSaldo.setPreferredSize(new java.awt.Dimension(189, 34));
        bConsultarSaldo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventanaPrincipal/bConsultarSaldoPR.png"))); // NOI18N
        bConsultarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultarSaldoActionPerformed(evt);
            }
        });

        bIngresarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventanaPrincipal/bIngEmpleado.png"))); // NOI18N
        bIngresarEmpleado.setPreferredSize(new java.awt.Dimension(189, 34));
        bIngresarEmpleado.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventanaPrincipal/bIngEmpleadoPR.png"))); // NOI18N
        bIngresarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIngresarEmpleadoActionPerformed(evt);
            }
        });

        bInformacionQueja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventanaPrincipal/bVerQueja.png"))); // NOI18N
        bInformacionQueja.setPreferredSize(new java.awt.Dimension(189, 34));
        bInformacionQueja.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventanaPrincipal/bVerQuejaPR.png"))); // NOI18N
        bInformacionQueja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInformacionQuejaActionPerformed(evt);
            }
        });

        bVerRutas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventanaPrincipal/bVerRutas.png"))); // NOI18N
        bVerRutas.setPreferredSize(new java.awt.Dimension(189, 34));
        bVerRutas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventanaPrincipal/bVerRutasPR.png"))); // NOI18N
        bVerRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerRutasActionPerformed(evt);
            }
        });

        bPlanViaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventanaPrincipal/bplanViaje.png"))); // NOI18N
        bPlanViaje.setPreferredSize(new java.awt.Dimension(189, 34));
        bPlanViaje.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventanaPrincipal/bplanViajePR.png"))); // NOI18N
        bPlanViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPlanViajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
        panelInferior.setLayout(panelInferiorLayout);
        panelInferiorLayout.setHorizontalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(bVerRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelInferiorLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bConsultarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bPersonalizarTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInferiorLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bIngresarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInferiorLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bInformacionQueja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bPlanViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bIngresarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInferiorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bModifcarDatosPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInferiorLayout.setVerticalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bPersonalizarTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bModifcarDatosPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bConsultarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPlanViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInferiorLayout.createSequentialGroup()
                        .addComponent(bVerRutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(bIngresarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInferiorLayout.createSequentialGroup()
                        .addComponent(bInformacionQueja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bIngresarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bIngresarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIngresarEmpleadoActionPerformed
                
        VentanaLogin vlogin = new VentanaLogin(this);
        vlogin.setVisible(true);
        this.setVisible(false);
                
    }//GEN-LAST:event_bIngresarEmpleadoActionPerformed

    private void bPersonalizarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPersonalizarTarjetaActionPerformed
        
        VentanaDatosPasajero vpersonalizar = new VentanaDatosPasajero(this, "Personalización de Tarjeta");
        vpersonalizar.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_bPersonalizarTarjetaActionPerformed

    private void bModifcarDatosPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModifcarDatosPasajeroActionPerformed
        
        VentanaDatosPasajero vmodificar = new VentanaDatosPasajero(this, "Modificación de Datos");
        vmodificar.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_bModifcarDatosPasajeroActionPerformed

    private void bConsultarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultarSaldoActionPerformed
        
        VentanaConsultaSaldo vConsultar = new VentanaConsultaSaldo(this);
        vConsultar.setVisible(true);
        vConsultar.tfPIN.setText("");
        vConsultar.lSaldo.setText("Saldo actual:");
        this.setEnabled(false);        
                
    }//GEN-LAST:event_bConsultarSaldoActionPerformed

    private void bPlanViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPlanViajeActionPerformed
        
        VentanaPlanViaje vPlan = new VentanaPlanViaje(this, "Plan de Viaje");
        vPlan.setVisible(true);                
        this.setVisible(false);
        
    }//GEN-LAST:event_bPlanViajeActionPerformed

    private void bVerRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerRutasActionPerformed
        
        VentanaPlanViaje vRuEstacion = new VentanaPlanViaje(this, "Rutas por Estación");
        vRuEstacion.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_bVerRutasActionPerformed

    private void bIngresarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIngresarRutaActionPerformed
        
        VentanaSimulacionIngreso vIngreso = new VentanaSimulacionIngreso(this);
        vIngreso.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_bIngresarRutaActionPerformed

    private void bInformacionQuejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInformacionQuejaActionPerformed
        
        VentanaInfoCaso vCaso = new VentanaInfoCaso(this);
        vCaso.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_bInformacionQuejaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConsultarSaldo;
    private javax.swing.JButton bInformacionQueja;
    private javax.swing.JButton bIngresarEmpleado;
    private javax.swing.JButton bIngresarRuta;
    private javax.swing.JButton bModifcarDatosPasajero;
    private javax.swing.JButton bPersonalizarTarjeta;
    private javax.swing.JButton bPlanViaje;
    private javax.swing.JButton bVerRutas;
    private javax.swing.JLabel labelEslogan;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperior;
    // End of variables declaration//GEN-END:variables
}
